language: ruby

rvm:
  - "1.8.7"
  - "1.9.3"
  - "2.0"
  - "2.2"
  - "2.4"
  - "2.5"

cache: bundler

env:
  global:
    - CC_TEST_REPORTER_ID=db60be1ae47fbdc5545366284a0a72be9c29d8fe7d7d5e42f16b2d61a19ed397

before_install:
  - gem update --system
  - gem install bundler

jobs:
  include:
    - script: bundle exec rake test
    - script: bundle exec rubocop
      rvm: "2.5"

# Code Climate before & after scripts
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

